// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public interface Busy_1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Busy_1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 value1 = 1;</code>
   */
  int getValue1();

  /**
   * <code>optional string string_value = 2;</code>
   */
  String getStringValue();
  /**
   * <code>optional string string_value = 2;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bool bool_value = 3;</code>
   */
  boolean getBoolValue();

  /**
   * <code>repeated .Vo_1 vos = 4;</code>
   */
  java.util.List<Vo_1>
      getVosList();
  /**
   * <code>repeated .Vo_1 vos = 4;</code>
   */
  Vo_1 getVos(int index);
  /**
   * <code>repeated .Vo_1 vos = 4;</code>
   */
  int getVosCount();
  /**
   * <code>repeated .Vo_1 vos = 4;</code>
   */
  java.util.List<? extends Vo_1OrBuilder>
      getVosOrBuilderList();
  /**
   * <code>repeated .Vo_1 vos = 4;</code>
   */
  Vo_1OrBuilder getVosOrBuilder(
          int index);
}
