// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public interface MsgBufOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MsgBuf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .MsgBuf.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .MsgBuf.Type type = 1;</code>
   */
  MsgBuf.Type getType();

  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  boolean hasSystemMsg();
  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  SystemMsg getSystemMsg();
  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  SystemMsgOrBuilder getSystemMsgOrBuilder();

  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  boolean hasRequestMsg();
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  RequestMsg getRequestMsg();
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  RequestMsgOrBuilder getRequestMsgOrBuilder();

  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  boolean hasResponseMsg();
  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  ResponseMsg getResponseMsg();
  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  ResponseMsgOrBuilder getResponseMsgOrBuilder();
}
