// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public final class MsgBufProto {
  private MsgBufProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgBuf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MsgBuf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Busy_1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Busy_1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vo_1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vo_1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013mtMsg.proto\"\266\001\n\006MsgBuf\022\032\n\004type\030\001 \001(\0162\014" +
      ".MsgBuf.Type\022\035\n\tsystemMsg\030\002 \001(\0132\n.System" +
      "Msg\022\037\n\nrequestMsg\030\003 \001(\0132\013.RequestMsg\022!\n\013" +
      "responseMsg\030\004 \001(\0132\014.ResponseMsg\"-\n\004Type\022" +
      "\n\n\006System\020\000\022\013\n\007Request\020\001\022\014\n\010Response\020\002\"\203" +
      "\001\n\tSystemMsg\022\035\n\004code\030\001 \001(\0162\017.SystemMsg.C" +
      "ode\022\016\n\006userId\030\002 \001(\t\022\013\n\003msg\030\003 \001(\t\":\n\004Code" +
      "\022\n\n\006Active\020\000\022\014\n\010Inactive\020\001\022\r\n\tHeartBeat\020" +
      "\002\022\t\n\005Close\020\005\"N\n\nRequestMsg\022\036\n\004code\030\001 \001(\016" +
      "2\020.RequestMsg.Code\022\r\n\005param\030\002 \001(\t\"\021\n\004Cod",
      "e\022\t\n\005busy1\020\000\"\254\001\n\013ResponseMsg\022#\n\006status\030\001" +
      " \001(\0162\023.ResponseMsg.Status\022\013\n\003msg\030\002 \001(\t\022\037" +
      "\n\004code\030\003 \001(\0162\021.ResponseMsg.Code\022\027\n\006busy_" +
      "1\030\004 \001(\0132\007.Busy_1\"\036\n\006Status\022\n\n\006sucess\020\000\022\010" +
      "\n\004fail\020\001\"\021\n\004Code\022\t\n\005busy1\020\000\"V\n\006Busy_1\022\016\n" +
      "\006value1\030\001 \001(\005\022\024\n\014string_value\030\002 \001(\t\022\022\n\nb" +
      "ool_value\030\003 \001(\010\022\022\n\003vos\030\004 \003(\0132\005.Vo_1\"@\n\004V" +
      "o_1\022\016\n\006value1\030\001 \001(\005\022\024\n\014string_value\030\002 \001(" +
      "\t\022\022\n\nbool_value\030\003 \001(\010B*\n\020com.mt.nio.prot" +
      "oB\013MsgBufProtoP\001\240\001\001\242\002\003GPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MsgBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MsgBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MsgBuf_descriptor,
        new String[] { "Type", "SystemMsg", "RequestMsg", "ResponseMsg", });
    internal_static_SystemMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SystemMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemMsg_descriptor,
        new String[] { "Code", "UserId", "Msg", });
    internal_static_RequestMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMsg_descriptor,
        new String[] { "Code", "Param", });
    internal_static_ResponseMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMsg_descriptor,
        new String[] { "Status", "Msg", "Code", "Busy1", });
    internal_static_Busy_1_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Busy_1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Busy_1_descriptor,
        new String[] { "Value1", "StringValue", "BoolValue", "Vos", });
    internal_static_Vo_1_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Vo_1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vo_1_descriptor,
        new String[] { "Value1", "StringValue", "BoolValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
