// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

/**
 * <pre>
 *结构体整体
 *	第一层分类：1 系统消息 2 请求消息 3 响应消息
 *  1 系统消息时，设定消息类型：  1活动状态 2非活动状态 3心跳消息 4关闭信道
 *  2 请求消息时，设定请求体：1 业务代码code 2 传入参数
 *  3 响应消息，设定响应内容：1 返回状态 2 返回消息 3 业务代码 4 业务返回值结构体
 * </pre>
 *
 * Protobuf type {@code MsgBuf}
 */
public  final class MsgBuf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MsgBuf)
    MsgBufOrBuilder {
  // Use MsgBuf.newBuilder() to construct.
  private MsgBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MsgBuf() {
    type_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MsgBuf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            SystemMsg.Builder subBuilder = null;
            if (systemMsg_ != null) {
              subBuilder = systemMsg_.toBuilder();
            }
            systemMsg_ = input.readMessage(SystemMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(systemMsg_);
              systemMsg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            RequestMsg.Builder subBuilder = null;
            if (requestMsg_ != null) {
              subBuilder = requestMsg_.toBuilder();
            }
            requestMsg_ = input.readMessage(RequestMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestMsg_);
              requestMsg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            ResponseMsg.Builder subBuilder = null;
            if (responseMsg_ != null) {
              subBuilder = responseMsg_.toBuilder();
            }
            responseMsg_ = input.readMessage(ResponseMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(responseMsg_);
              responseMsg_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MsgBufProto.internal_static_MsgBuf_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MsgBufProto.internal_static_MsgBuf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MsgBuf.class, Builder.class);
  }

  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * Protobuf enum {@code MsgBuf.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>System = 0;</code>
     */
    System(0),
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>Request = 1;</code>
     */
    Request(1),
    /**
     * <pre>
     *响应体
     * </pre>
     *
     * <code>Response = 2;</code>
     */
    Response(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>System = 0;</code>
     */
    public static final int System_VALUE = 0;
    /**
     * <pre>
     *请求体
     * </pre>
     *
     * <code>Request = 1;</code>
     */
    public static final int Request_VALUE = 1;
    /**
     * <pre>
     *响应体
     * </pre>
     *
     * <code>Response = 2;</code>
     */
    public static final int Response_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return System;
        case 1: return Request;
        case 2: return Response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MsgBuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgBuf.Type)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .MsgBuf.Type type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .MsgBuf.Type type = 1;</code>
   */
  public Type getType() {
    Type result = Type.valueOf(type_);
    return result == null ? Type.UNRECOGNIZED : result;
  }

  public static final int SYSTEMMSG_FIELD_NUMBER = 2;
  private SystemMsg systemMsg_;
  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  public boolean hasSystemMsg() {
    return systemMsg_ != null;
  }
  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  public SystemMsg getSystemMsg() {
    return systemMsg_ == null ? SystemMsg.getDefaultInstance() : systemMsg_;
  }
  /**
   * <pre>
   *系统消息体
   * </pre>
   *
   * <code>optional .SystemMsg systemMsg = 2;</code>
   */
  public SystemMsgOrBuilder getSystemMsgOrBuilder() {
    return getSystemMsg();
  }

  public static final int REQUESTMSG_FIELD_NUMBER = 3;
  private RequestMsg requestMsg_;
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  public boolean hasRequestMsg() {
    return requestMsg_ != null;
  }
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  public RequestMsg getRequestMsg() {
    return requestMsg_ == null ? RequestMsg.getDefaultInstance() : requestMsg_;
  }
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * <code>optional .RequestMsg requestMsg = 3;</code>
   */
  public RequestMsgOrBuilder getRequestMsgOrBuilder() {
    return getRequestMsg();
  }

  public static final int RESPONSEMSG_FIELD_NUMBER = 4;
  private ResponseMsg responseMsg_;
  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  public boolean hasResponseMsg() {
    return responseMsg_ != null;
  }
  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  public ResponseMsg getResponseMsg() {
    return responseMsg_ == null ? ResponseMsg.getDefaultInstance() : responseMsg_;
  }
  /**
   * <pre>
   *响应消息体
   * </pre>
   *
   * <code>optional .ResponseMsg responseMsg = 4;</code>
   */
  public ResponseMsgOrBuilder getResponseMsgOrBuilder() {
    return getResponseMsg();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != Type.System.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (systemMsg_ != null) {
      output.writeMessage(2, getSystemMsg());
    }
    if (requestMsg_ != null) {
      output.writeMessage(3, getRequestMsg());
    }
    if (responseMsg_ != null) {
      output.writeMessage(4, getResponseMsg());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != Type.System.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (systemMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSystemMsg());
    }
    if (requestMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRequestMsg());
    }
    if (responseMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getResponseMsg());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MsgBuf)) {
      return super.equals(obj);
    }
    MsgBuf other = (MsgBuf) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (hasSystemMsg() == other.hasSystemMsg());
    if (hasSystemMsg()) {
      result = result && getSystemMsg()
          .equals(other.getSystemMsg());
    }
    result = result && (hasRequestMsg() == other.hasRequestMsg());
    if (hasRequestMsg()) {
      result = result && getRequestMsg()
          .equals(other.getRequestMsg());
    }
    result = result && (hasResponseMsg() == other.hasResponseMsg());
    if (hasResponseMsg()) {
      result = result && getResponseMsg()
          .equals(other.getResponseMsg());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasSystemMsg()) {
      hash = (37 * hash) + SYSTEMMSG_FIELD_NUMBER;
      hash = (53 * hash) + getSystemMsg().hashCode();
    }
    if (hasRequestMsg()) {
      hash = (37 * hash) + REQUESTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMsg().hashCode();
    }
    if (hasResponseMsg()) {
      hash = (37 * hash) + RESPONSEMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMsg().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MsgBuf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MsgBuf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MsgBuf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MsgBuf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MsgBuf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MsgBuf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MsgBuf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MsgBuf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MsgBuf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MsgBuf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MsgBuf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *结构体整体
   *	第一层分类：1 系统消息 2 请求消息 3 响应消息
   *  1 系统消息时，设定消息类型：  1活动状态 2非活动状态 3心跳消息 4关闭信道
   *  2 请求消息时，设定请求体：1 业务代码code 2 传入参数
   *  3 响应消息，设定响应内容：1 返回状态 2 返回消息 3 业务代码 4 业务返回值结构体
   * </pre>
   *
   * Protobuf type {@code MsgBuf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MsgBuf)
          MsgBufOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgBufProto.internal_static_MsgBuf_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgBufProto.internal_static_MsgBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgBuf.class, Builder.class);
    }

    // Construct using MsgBuf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (systemMsgBuilder_ == null) {
        systemMsg_ = null;
      } else {
        systemMsg_ = null;
        systemMsgBuilder_ = null;
      }
      if (requestMsgBuilder_ == null) {
        requestMsg_ = null;
      } else {
        requestMsg_ = null;
        requestMsgBuilder_ = null;
      }
      if (responseMsgBuilder_ == null) {
        responseMsg_ = null;
      } else {
        responseMsg_ = null;
        responseMsgBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MsgBufProto.internal_static_MsgBuf_descriptor;
    }

    public MsgBuf getDefaultInstanceForType() {
      return MsgBuf.getDefaultInstance();
    }

    public MsgBuf build() {
      MsgBuf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public MsgBuf buildPartial() {
      MsgBuf result = new MsgBuf(this);
      result.type_ = type_;
      if (systemMsgBuilder_ == null) {
        result.systemMsg_ = systemMsg_;
      } else {
        result.systemMsg_ = systemMsgBuilder_.build();
      }
      if (requestMsgBuilder_ == null) {
        result.requestMsg_ = requestMsg_;
      } else {
        result.requestMsg_ = requestMsgBuilder_.build();
      }
      if (responseMsgBuilder_ == null) {
        result.responseMsg_ = responseMsg_;
      } else {
        result.responseMsg_ = responseMsgBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MsgBuf) {
        return mergeFrom((MsgBuf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MsgBuf other) {
      if (other == MsgBuf.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasSystemMsg()) {
        mergeSystemMsg(other.getSystemMsg());
      }
      if (other.hasRequestMsg()) {
        mergeRequestMsg(other.getRequestMsg());
      }
      if (other.hasResponseMsg()) {
        mergeResponseMsg(other.getResponseMsg());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MsgBuf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MsgBuf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .MsgBuf.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .MsgBuf.Type type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .MsgBuf.Type type = 1;</code>
     */
    public Type getType() {
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .MsgBuf.Type type = 1;</code>
     */
    public Builder setType(Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .MsgBuf.Type type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private SystemMsg systemMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            SystemMsg, SystemMsg.Builder, SystemMsgOrBuilder> systemMsgBuilder_;
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public boolean hasSystemMsg() {
      return systemMsgBuilder_ != null || systemMsg_ != null;
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public SystemMsg getSystemMsg() {
      if (systemMsgBuilder_ == null) {
        return systemMsg_ == null ? SystemMsg.getDefaultInstance() : systemMsg_;
      } else {
        return systemMsgBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public Builder setSystemMsg(SystemMsg value) {
      if (systemMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        systemMsg_ = value;
        onChanged();
      } else {
        systemMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public Builder setSystemMsg(
        SystemMsg.Builder builderForValue) {
      if (systemMsgBuilder_ == null) {
        systemMsg_ = builderForValue.build();
        onChanged();
      } else {
        systemMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public Builder mergeSystemMsg(SystemMsg value) {
      if (systemMsgBuilder_ == null) {
        if (systemMsg_ != null) {
          systemMsg_ =
            SystemMsg.newBuilder(systemMsg_).mergeFrom(value).buildPartial();
        } else {
          systemMsg_ = value;
        }
        onChanged();
      } else {
        systemMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public Builder clearSystemMsg() {
      if (systemMsgBuilder_ == null) {
        systemMsg_ = null;
        onChanged();
      } else {
        systemMsg_ = null;
        systemMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public SystemMsg.Builder getSystemMsgBuilder() {
      
      onChanged();
      return getSystemMsgFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    public SystemMsgOrBuilder getSystemMsgOrBuilder() {
      if (systemMsgBuilder_ != null) {
        return systemMsgBuilder_.getMessageOrBuilder();
      } else {
        return systemMsg_ == null ?
            SystemMsg.getDefaultInstance() : systemMsg_;
      }
    }
    /**
     * <pre>
     *系统消息体
     * </pre>
     *
     * <code>optional .SystemMsg systemMsg = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            SystemMsg, SystemMsg.Builder, SystemMsgOrBuilder>
        getSystemMsgFieldBuilder() {
      if (systemMsgBuilder_ == null) {
        systemMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                SystemMsg, SystemMsg.Builder, SystemMsgOrBuilder>(
                getSystemMsg(),
                getParentForChildren(),
                isClean());
        systemMsg_ = null;
      }
      return systemMsgBuilder_;
    }

    private RequestMsg requestMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            RequestMsg, RequestMsg.Builder, RequestMsgOrBuilder> requestMsgBuilder_;
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public boolean hasRequestMsg() {
      return requestMsgBuilder_ != null || requestMsg_ != null;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public RequestMsg getRequestMsg() {
      if (requestMsgBuilder_ == null) {
        return requestMsg_ == null ? RequestMsg.getDefaultInstance() : requestMsg_;
      } else {
        return requestMsgBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public Builder setRequestMsg(RequestMsg value) {
      if (requestMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestMsg_ = value;
        onChanged();
      } else {
        requestMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public Builder setRequestMsg(
        RequestMsg.Builder builderForValue) {
      if (requestMsgBuilder_ == null) {
        requestMsg_ = builderForValue.build();
        onChanged();
      } else {
        requestMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public Builder mergeRequestMsg(RequestMsg value) {
      if (requestMsgBuilder_ == null) {
        if (requestMsg_ != null) {
          requestMsg_ =
            RequestMsg.newBuilder(requestMsg_).mergeFrom(value).buildPartial();
        } else {
          requestMsg_ = value;
        }
        onChanged();
      } else {
        requestMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public Builder clearRequestMsg() {
      if (requestMsgBuilder_ == null) {
        requestMsg_ = null;
        onChanged();
      } else {
        requestMsg_ = null;
        requestMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public RequestMsg.Builder getRequestMsgBuilder() {
      
      onChanged();
      return getRequestMsgFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    public RequestMsgOrBuilder getRequestMsgOrBuilder() {
      if (requestMsgBuilder_ != null) {
        return requestMsgBuilder_.getMessageOrBuilder();
      } else {
        return requestMsg_ == null ?
            RequestMsg.getDefaultInstance() : requestMsg_;
      }
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * <code>optional .RequestMsg requestMsg = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            RequestMsg, RequestMsg.Builder, RequestMsgOrBuilder>
        getRequestMsgFieldBuilder() {
      if (requestMsgBuilder_ == null) {
        requestMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                RequestMsg, RequestMsg.Builder, RequestMsgOrBuilder>(
                getRequestMsg(),
                getParentForChildren(),
                isClean());
        requestMsg_ = null;
      }
      return requestMsgBuilder_;
    }

    private ResponseMsg responseMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            ResponseMsg, ResponseMsg.Builder, ResponseMsgOrBuilder> responseMsgBuilder_;
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public boolean hasResponseMsg() {
      return responseMsgBuilder_ != null || responseMsg_ != null;
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public ResponseMsg getResponseMsg() {
      if (responseMsgBuilder_ == null) {
        return responseMsg_ == null ? ResponseMsg.getDefaultInstance() : responseMsg_;
      } else {
        return responseMsgBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public Builder setResponseMsg(ResponseMsg value) {
      if (responseMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseMsg_ = value;
        onChanged();
      } else {
        responseMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public Builder setResponseMsg(
        ResponseMsg.Builder builderForValue) {
      if (responseMsgBuilder_ == null) {
        responseMsg_ = builderForValue.build();
        onChanged();
      } else {
        responseMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public Builder mergeResponseMsg(ResponseMsg value) {
      if (responseMsgBuilder_ == null) {
        if (responseMsg_ != null) {
          responseMsg_ =
            ResponseMsg.newBuilder(responseMsg_).mergeFrom(value).buildPartial();
        } else {
          responseMsg_ = value;
        }
        onChanged();
      } else {
        responseMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public Builder clearResponseMsg() {
      if (responseMsgBuilder_ == null) {
        responseMsg_ = null;
        onChanged();
      } else {
        responseMsg_ = null;
        responseMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public ResponseMsg.Builder getResponseMsgBuilder() {
      
      onChanged();
      return getResponseMsgFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    public ResponseMsgOrBuilder getResponseMsgOrBuilder() {
      if (responseMsgBuilder_ != null) {
        return responseMsgBuilder_.getMessageOrBuilder();
      } else {
        return responseMsg_ == null ?
            ResponseMsg.getDefaultInstance() : responseMsg_;
      }
    }
    /**
     * <pre>
     *响应消息体
     * </pre>
     *
     * <code>optional .ResponseMsg responseMsg = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            ResponseMsg, ResponseMsg.Builder, ResponseMsgOrBuilder>
        getResponseMsgFieldBuilder() {
      if (responseMsgBuilder_ == null) {
        responseMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                ResponseMsg, ResponseMsg.Builder, ResponseMsgOrBuilder>(
                getResponseMsg(),
                getParentForChildren(),
                isClean());
        responseMsg_ = null;
      }
      return responseMsgBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:MsgBuf)
  }

  // @@protoc_insertion_point(class_scope:MsgBuf)
  private static final MsgBuf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MsgBuf();
  }

  public static MsgBuf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsgBuf>
      PARSER = new com.google.protobuf.AbstractParser<MsgBuf>() {
    public MsgBuf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgBuf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MsgBuf> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MsgBuf> getParserForType() {
    return PARSER;
  }

  public MsgBuf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

