// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public interface RequestMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RequestMsg.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>optional .RequestMsg.Code code = 1;</code>
   */
  RequestMsg.Code getCode();

  /**
   * <code>optional string param = 2;</code>
   */
  String getParam();
  /**
   * <code>optional string param = 2;</code>
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
