// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

/**
 * Protobuf type {@code ResponseMsg}
 */
public  final class ResponseMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResponseMsg)
    ResponseMsgOrBuilder {
  // Use ResponseMsg.newBuilder() to construct.
  private ResponseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseMsg() {
    status_ = 0;
    msg_ = "";
    code_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ResponseMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 34: {
            Busy_1.Builder subBuilder = null;
            if (busy1_ != null) {
              subBuilder = busy1_.toBuilder();
            }
            busy1_ = input.readMessage(Busy_1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(busy1_);
              busy1_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MsgBufProto.internal_static_ResponseMsg_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MsgBufProto.internal_static_ResponseMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResponseMsg.class, Builder.class);
  }

  /**
   * <pre>
   *返回状态值和返回消息
   * </pre>
   *
   * Protobuf enum {@code ResponseMsg.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>sucess = 0;</code>
     */
    sucess(0),
    /**
     * <code>fail = 1;</code>
     */
    fail(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>sucess = 0;</code>
     */
    public static final int sucess_VALUE = 0;
    /**
     * <code>fail = 1;</code>
     */
    public static final int fail_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return sucess;
        case 1: return fail;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ResponseMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseMsg.Status)
  }

  /**
   * <pre>
   *业务代码code
   * </pre>
   *
   * Protobuf enum {@code ResponseMsg.Code}
   */
  public enum Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>busy1 = 0;</code>
     */
    busy1(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>busy1 = 0;</code>
     */
    public static final int busy1_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Code valueOf(int value) {
      return forNumber(value);
    }

    public static Code forNumber(int value) {
      switch (value) {
        case 0: return busy1;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Code>() {
            public Code findValueByNumber(int number) {
              return Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ResponseMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseMsg.Code)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>optional .ResponseMsg.Status status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .ResponseMsg.Status status = 1;</code>
   */
  public Status getStatus() {
    Status result = Status.valueOf(status_);
    return result == null ? Status.UNRECOGNIZED : result;
  }

  public static final int MSG_FIELD_NUMBER = 2;
  private volatile Object msg_;
  /**
   * <code>optional string msg = 2;</code>
   */
  public String getMsg() {
    Object ref = msg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string msg = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    Object ref = msg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 3;
  private int code_;
  /**
   * <code>optional .ResponseMsg.Code code = 3;</code>
   */
  public int getCodeValue() {
    return code_;
  }
  /**
   * <code>optional .ResponseMsg.Code code = 3;</code>
   */
  public Code getCode() {
    Code result = Code.valueOf(code_);
    return result == null ? Code.UNRECOGNIZED : result;
  }

  public static final int BUSY_1_FIELD_NUMBER = 4;
  private Busy_1 busy1_;
  /**
   * <pre>
   *业务1的返回结构体
   * </pre>
   *
   * <code>optional .Busy_1 busy_1 = 4;</code>
   */
  public boolean hasBusy1() {
    return busy1_ != null;
  }
  /**
   * <pre>
   *业务1的返回结构体
   * </pre>
   *
   * <code>optional .Busy_1 busy_1 = 4;</code>
   */
  public Busy_1 getBusy1() {
    return busy1_ == null ? Busy_1.getDefaultInstance() : busy1_;
  }
  /**
   * <pre>
   *业务1的返回结构体
   * </pre>
   *
   * <code>optional .Busy_1 busy_1 = 4;</code>
   */
  public Busy_1OrBuilder getBusy1OrBuilder() {
    return getBusy1();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != Status.sucess.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
    }
    if (code_ != Code.busy1.getNumber()) {
      output.writeEnum(3, code_);
    }
    if (busy1_ != null) {
      output.writeMessage(4, getBusy1());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != Status.sucess.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
    }
    if (code_ != Code.busy1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, code_);
    }
    if (busy1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBusy1());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResponseMsg)) {
      return super.equals(obj);
    }
    ResponseMsg other = (ResponseMsg) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && code_ == other.code_;
    result = result && (hasBusy1() == other.hasBusy1());
    if (hasBusy1()) {
      result = result && getBusy1()
          .equals(other.getBusy1());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    if (hasBusy1()) {
      hash = (37 * hash) + BUSY_1_FIELD_NUMBER;
      hash = (53 * hash) + getBusy1().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResponseMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResponseMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResponseMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResponseMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResponseMsg)
          ResponseMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgBufProto.internal_static_ResponseMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgBufProto.internal_static_ResponseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseMsg.class, Builder.class);
    }

    // Construct using ResponseMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      msg_ = "";

      code_ = 0;

      if (busy1Builder_ == null) {
        busy1_ = null;
      } else {
        busy1_ = null;
        busy1Builder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MsgBufProto.internal_static_ResponseMsg_descriptor;
    }

    public ResponseMsg getDefaultInstanceForType() {
      return ResponseMsg.getDefaultInstance();
    }

    public ResponseMsg build() {
      ResponseMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ResponseMsg buildPartial() {
      ResponseMsg result = new ResponseMsg(this);
      result.status_ = status_;
      result.msg_ = msg_;
      result.code_ = code_;
      if (busy1Builder_ == null) {
        result.busy1_ = busy1_;
      } else {
        result.busy1_ = busy1Builder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResponseMsg) {
        return mergeFrom((ResponseMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResponseMsg other) {
      if (other == ResponseMsg.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (other.hasBusy1()) {
        mergeBusy1(other.getBusy1());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResponseMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResponseMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .ResponseMsg.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .ResponseMsg.Status status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ResponseMsg.Status status = 1;</code>
     */
    public Status getStatus() {
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .ResponseMsg.Status status = 1;</code>
     */
    public Builder setStatus(Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ResponseMsg.Status status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private Object msg_ = "";
    /**
     * <code>optional string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private int code_ = 0;
    /**
     * <code>optional .ResponseMsg.Code code = 3;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>optional .ResponseMsg.Code code = 3;</code>
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ResponseMsg.Code code = 3;</code>
     */
    public Code getCode() {
      Code result = Code.valueOf(code_);
      return result == null ? Code.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .ResponseMsg.Code code = 3;</code>
     */
    public Builder setCode(Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ResponseMsg.Code code = 3;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private Busy_1 busy1_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Busy_1, Busy_1.Builder, Busy_1OrBuilder> busy1Builder_;
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public boolean hasBusy1() {
      return busy1Builder_ != null || busy1_ != null;
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Busy_1 getBusy1() {
      if (busy1Builder_ == null) {
        return busy1_ == null ? Busy_1.getDefaultInstance() : busy1_;
      } else {
        return busy1Builder_.getMessage();
      }
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Builder setBusy1(Busy_1 value) {
      if (busy1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        busy1_ = value;
        onChanged();
      } else {
        busy1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Builder setBusy1(
        Busy_1.Builder builderForValue) {
      if (busy1Builder_ == null) {
        busy1_ = builderForValue.build();
        onChanged();
      } else {
        busy1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Builder mergeBusy1(Busy_1 value) {
      if (busy1Builder_ == null) {
        if (busy1_ != null) {
          busy1_ =
            Busy_1.newBuilder(busy1_).mergeFrom(value).buildPartial();
        } else {
          busy1_ = value;
        }
        onChanged();
      } else {
        busy1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Builder clearBusy1() {
      if (busy1Builder_ == null) {
        busy1_ = null;
        onChanged();
      } else {
        busy1_ = null;
        busy1Builder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Busy_1.Builder getBusy1Builder() {
      
      onChanged();
      return getBusy1FieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    public Busy_1OrBuilder getBusy1OrBuilder() {
      if (busy1Builder_ != null) {
        return busy1Builder_.getMessageOrBuilder();
      } else {
        return busy1_ == null ?
            Busy_1.getDefaultInstance() : busy1_;
      }
    }
    /**
     * <pre>
     *业务1的返回结构体
     * </pre>
     *
     * <code>optional .Busy_1 busy_1 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Busy_1, Busy_1.Builder, Busy_1OrBuilder>
        getBusy1FieldBuilder() {
      if (busy1Builder_ == null) {
        busy1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Busy_1, Busy_1.Builder, Busy_1OrBuilder>(
                getBusy1(),
                getParentForChildren(),
                isClean());
        busy1_ = null;
      }
      return busy1Builder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ResponseMsg)
  }

  // @@protoc_insertion_point(class_scope:ResponseMsg)
  private static final ResponseMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResponseMsg();
  }

  public static ResponseMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseMsg>
      PARSER = new com.google.protobuf.AbstractParser<ResponseMsg>() {
    public ResponseMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseMsg> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResponseMsg> getParserForType() {
    return PARSER;
  }

  public ResponseMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

