// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public interface SystemMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SystemMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .SystemMsg.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>optional .SystemMsg.Code code = 1;</code>
   */
  SystemMsg.Code getCode();

  /**
   * <code>optional string userId = 2;</code>
   */
  String getUserId();
  /**
   * <code>optional string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string msg = 3;</code>
   */
  String getMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
