// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtMsg.proto

package com.time.memory.mt.nio.proto;

public interface Vo_1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vo_1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 value1 = 1;</code>
   */
  int getValue1();

  /**
   * <code>optional string string_value = 2;</code>
   */
  String getStringValue();
  /**
   * <code>optional string string_value = 2;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bool bool_value = 3;</code>
   */
  boolean getBoolValue();
}
